import * as Yup from 'yup';

export const PatientRegistrationValidationSchema = Yup.object().shape({
  title: Yup.string(),
  firstName: Yup.string().required('First name is required'),
  lastName: Yup.string(),
  gender: Yup.string().required('Gender is required'),
  dob: Yup.date()
    .required('Date of birth is required')
    .max(new Date(), 'Date of birth cannot be in the future'),
  education: Yup.string(),
  maritalStatus: Yup.string().required('Marital Status is required'),
  bloodGroup: Yup.string(),
  countryBirth: Yup.string(),
  nationality: Yup.string().required('Nationality is required'),
  motherTounge: Yup.string(),
  occupation: Yup.string().required('Occupation is required'),
  religion: Yup.string().required('Religion is required'),
  mobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ).required('Mobile number is required'),
  alernativeMobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ),
  email: Yup.string().email('Invalid email format').required('Email is required'),
  dependentType: Yup.string(),
  dependentName: Yup.string(),
  dependentRelation: Yup.string(),
  dependentMobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ),
  dependentEmail: Yup.string(),
  addressLine1: Yup.string().required('Address Line 1 is required'),
  addressLine2: Yup.string(),
  state: Yup.string().required('State is required'),
  city: Yup.string().required('City is required'),
  pincode: Yup.string().required('Pincode is required'),
  // country: Yup.string().required("Country is required"),
  idProofType: Yup.string().required('ID proof type is required'),
  idProofNumber: Yup.string().required('ID proof number is required'),
  idProofIssuedCountry: Yup.string(),
  ABHANumber: Yup.string(),
  reasonOfVisit: Yup.string().required('Reason of visit is required'),
  referredBy: Yup.string(),
  referredByOther: Yup.string(),
  referredByDoctor: Yup.string(),
  marketingSource: Yup.string(),
  intepreter: Yup.boolean(),
  intepreteName: Yup.string(),
  isPatientSurrogate: Yup.boolean(),
  isPatientDeceased: Yup.boolean(),
  detailsOfDeath: Yup.string(),
  isPatientInsured: Yup.boolean(),
  // insuranceCompany: Yup.string(),
  insuranceSponsorName: Yup.string(),
  insurancePolicyNumber: Yup.string(),
  insurancePolicyHolderName: Yup.string(),
  insuranceAmountEligible: Yup.string(),
  image: Yup.mixed(),
  remarks: Yup.string(),
});

export const PartnerRegistrationValidationSchema = Yup.object().shape({
  title: Yup.string(),
  firstName: Yup.string().required('First name is required'),
  lastName: Yup.string(),
  gender: Yup.string().required('Gender is required'),
  dob: Yup.date()
    .required('Date of birth is required')
    .max(new Date(), 'Date of birth cannot be in the future'),
  education: Yup.string(),
  maritalStatus: Yup.string().required('Marital Status is required'),
  bloodGroup: Yup.string(),
  countryBirth: Yup.string(),
  motherTounge: Yup.string(),
  occupation: Yup.string().required('Occupation is required'),
  mobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ).required('Mobile Number is required'),
  alernativeMobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ),
  email: Yup.string().email('Invalid email format').required('Email is required'),
  dependentType: Yup.string(),
  dependentName: Yup.string(),
  dependentRelation: Yup.string(),
  dependentMobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ),
  dependentEmail: Yup.string().email('Invalid email format'),
  addressLine1: Yup.string().required('Address Line 1 is required'),
  addressLine2: Yup.string(),
  state: Yup.string().required('State is required'),
  city: Yup.string().required('City is required'),
  pincode: Yup.string().required('Pincode is required'),
  // country: Yup.string().required("Country is required"),
  idProofType: Yup.string().required('ID proof type is required'),
  idProofNumber: Yup.string().required('ID proof number is required'),
  idProofIssuedCountry: Yup.string(),
  ABHANumber: Yup.string(),
  referredBy: Yup.string(),
  referredByOther: Yup.string(),
  referredByDoctor: Yup.string(),
  intepreter: Yup.boolean(),
  intepreteName: Yup.string(),
  isPatientSurrogate: Yup.boolean(),
  isPatientDeceased: Yup.boolean(),
  detailsOfDeath: Yup.string(),
  isPatientInsured: Yup.boolean(),
  // insuranceCompany: Yup.string(),
  insuranceSponsorName: Yup.string(),
  insurancePolicyNumber: Yup.string(),
  insurancePolicyHolderName: Yup.string(),
  insuranceAmountEligible: Yup.string(),
  image: Yup.mixed(),
  remarks: Yup.string(),
});

export const DonorRegistrationfrombankValidationSchema = Yup.object().shape({
  title: Yup.string(),
  firstName: Yup.string().required('First name is required'),
  lastName: Yup.string(),
  gender: Yup.string().required('Gender is required'),
  dob: Yup.date().required('Date of birth is required'),
  education: Yup.string(),
  maritalStatus: Yup.string().required('Marital status is required'),
  bloodGroup: Yup.string(),
  countryBirth: Yup.string(),
  nationality: Yup.string().required('Nationality is required'),
  motherTounge: Yup.string(),
  occupation: Yup.string().required('Occupation is required'),
  religion: Yup.string().required('Religion is required'),
  mobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ).required('Mobile number is required'),
  alernativeMobile: Yup.string().matches(
    /^(\+\d{1,3}\s?)?\d{10,13}$/,
    'Enter Valid Phone Number',
  ),
  email: Yup.string().email('Invalid email format').required('Email is required'),
  dependentType: Yup.boolean(),

  addressLine1: Yup.string().required('Address line 1 is required'),
  addressLine2: Yup.string(),
  state: Yup.string().required('State is required'),
  city: Yup.string().required('City is required'),
  pincode: Yup.string().required('Pincode is required'),
  idProofType: Yup.string().required('ID proof type is required'),
  idProofNumber: Yup.string().required('ID proof number is required'),
  idProofIssuedCountry: Yup.string(),
  ABHANumber: Yup.string(),
  interpreter: Yup.boolean(),
  isDonor: Yup.boolean(),
  hiv: Yup.string(),
  height: Yup.string(),
  Build: Yup.string(),
  Ethnicity: Yup.string(),
  HealthLooks: Yup.string(),
  faceColour: Yup.string(),
  eyeColour: Yup.string(),
  haircolour: Yup.string(),
  RHantibody: Yup.string(),
  skinTone: Yup.string(),
  complexion: Yup.string(),
  referrerName: Yup.string(),
  marketingSource: Yup.string(),
  intepreter: Yup.boolean(),
  congenitaldeformities: Yup.boolean(),
  geneticAcquiredDisease: Yup.string(),
  historyOfChronicIllness: Yup.string(),
  seriousDisease: Yup.string(),
  seriousDiseaserelative: Yup.string(),
  isPatientInsured: Yup.boolean(),
  remarks: Yup.string(),
});

export const DonorRegistrationValidationSchemaFromHospital = Yup.object().shape(
  {
    title: Yup.string(),
    firstName: Yup.string().required('First name is required'),
    lastName: Yup.string(),
    gender: Yup.string().required('Gender  is required'),
    dob: Yup.string().required('Date of birth is required'),
    education: Yup.string(),
    maritalStatus: Yup.string().required('Martial Status  is required'),
    bloodGroup: Yup.string(),
    countryBirth: Yup.string(),
    nationality: Yup.string().required('Nationality is required'),
    motherTounge: Yup.string(),
    occupation: Yup.string().required('Occupation is required'),
    religion: Yup.string(),
    mobile: Yup.string().matches(
      /^(\+\d{1,3}\s?)?\d{10,13}$/,
      'Enter Valid Phone Number',
    ).required('Mobile number is required'),
    alernativeMobile: Yup.string().matches(
      /^(\+\d{1,3}\s?)?\d{10,13}$/,
      'Enter Valid Phone Number',
    ),
    email: Yup.string().email('Invalid email format').required('Email is required'),
    dependentType: Yup.string(),
    dependentName: Yup.string(),
    dependentRelation: Yup.string(),
    dependentMobile: Yup.string().matches(
      /^(\+\d{1,3}\s?)?\d{10,13}$/,
      'Enter Valid Phone Number',
    ),
    dependentEmail: Yup.string(),
    addressLine1: Yup.string().required('Address Line 1 is required'),
    addressLine2: Yup.string(),
    state: Yup.string().required('State is required'),
    city: Yup.string().required('City is required'),
    pincode: Yup.string().required('Pincode is required'),
    // country: Yup.string().required("Country is required"),
    idProofType: Yup.string().required('ID proof type is required'),
    idProofNumber: Yup.string().required('ID proof number is required'),
    idProofIssuedCountry: Yup.string(),
    ABHANumber: Yup.string(),
    reasonOfVisit: Yup.string(),
    referredBy: Yup.string(),
    referredByOther: Yup.string(),
    referredByDoctor: Yup.string(),
    marketingSource: Yup.string(),
    intepreter: Yup.boolean(),
    intepreteName: Yup.string(),
    isPatientSurrogate: Yup.boolean(),
    isPatientDeceased: Yup.boolean(),
    detailsOfDeath: Yup.string(),
    isPatientInsured: Yup.boolean(),
    // insuranceCompany: Yup.string(),
    insuranceSponsorName: Yup.string(),
    insurancePolicyNumber: Yup.string(),
    insurancePolicyHolderName: Yup.string(),
    insuranceAmountEligible: Yup.string(),
    image: Yup.mixed(),
    remarks: Yup.string(),
  },
);
