import { ICase } from './case';
import { IDonor } from './donor';

export interface IPatient {
  _id: string;
  clinicId: string;
  branchId: string;
  title: string;
  firstName: string;
  lastName: string;
  gender: string;
  age: number;
  dob: string;
  education: string;
  maritalStatus: string;
  bloodGroup: string;
  countryBirth: string;
  nationality: string;
  motherTounge: string;
  occupation: string;
  religion: string;
  mobile: string;
  alernativeMobile: string;
  email: string;
  dependentType: string;
  dependentName: string;
  dependentRelation: string;
  dependentMobile: string;
  dependentEmail: string;
  addressLine1: string;
  addressLine2: string;
  state: string;
  city: string;
  pincode: string;
  idProofType: string;
  idProofNumber: string;
  idProofIssuedCountry: string;
  ABHANumber: string;
  reasonOfVisit: string;
  referredBy: string;
  marketingSource: string;
  intepreter: boolean;
  isPatientSurrogate: boolean;
  isPatientDeceased: boolean;
  detailsOfDeath: string;
  isPatientInsured: boolean;
  insuranceSponsorName: string;
  insurancePolicyNumber: string;
  insurancePolicyHolderName: string;
  insuranceAmountEligible: string;
  image: string;
  remarks: string;
  status: string;
  createdAt: Date;
  updatedAt: Date;
  patientId: string;
  __v: number;
  case: ICase;
  donor: IDonor;
  appointment: {
    upcomingAppointment: string;
    lastAppointment: string;
  };
  partnerDetails: IPatient;
  referrerName: string;
  intepreterName: string;
  identifications: string;
}
