import ArticleIcon from "@mui/icons-material/Article";

export const navList: any[] = [
  {
    id: 0,
    title: "Console",
    path: "/",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 1,
    title: "IVF Registration",
    path: "/ivf-registration",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 2,
    title: "Patients",
    path: "/patients",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 3,
    title: "Appointments",
    path: "/appointments",
    icon: ArticleIcon,
    onSelect: () => {},
  },
];

export const patientNavList: any[] = [
  {
    id: 0,
    title: "Home",
    path: "/",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 1,
    title: "Demographics",
    path: "/demographics",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 2,
    title: "Patient History",
    path: "/history",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 3,
    title: "Visit History",
    path: "/visit-history",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 4,
    title: "Medical Records",
    path: "/medical-records",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 5,
    title: "Investigations",
    path: "/investigations",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 6,
    title: "Ultra Sound",
    path: "/ultra-sound",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 7,
    title: "HYS / LAP Summary",
    path: "/hys-lap-summary",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 8,
    title: "Treatment",
    path: "/treatment",
    icon: ArticleIcon,
    onSelect: () => {},
    isAccordion: true,
    accordionItems: [
      {
        id: 0,
        title: "Treatment Cycle",
        path: "/treatment/treatment-cycle",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 1,
        title: "OOCYTE Aspiration Report",
        path: "/treatment/oocyte-aspiration-report",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 2,
        title: "Treatment Drugs",
        path: "/treatment/treatment-drugs",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 3,
        title: "Cycle / Pregnancy Outcome",
        path: "/treatment/cycle-pregnancy-outcome",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 4,
        title: "Cycle Summary",
        path: "/treatment/cycle-summary",
        icon: null,
        onSelect: () => {},
      },
    ],
  },
  {
    id: 9,
    title: "Andrology",
    path: "/andrology",
    icon: ArticleIcon,
    onSelect: () => {},
    isAccordion: true,
    accordionItems: [
      {
        id: 0,
        title: "Semen Analysis",
        path: "/andrology/semen-analysis",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 1,
        title: "Sperm DFI",
        path: "/andrology/sperm-dfi",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 2,
        title: "Sperm Freezing",
        path: "/andrology/sperm-freezing",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 3,
        title: "Sperm Preparation",
        path: "/andrology/sperm-preparation",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 4,
        title: "IUI-H",
        path: "/andrology/iui-h",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 5,
        title: "IUI-D",
        path: "/andrology/iui-d",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 6,
        title: "TESA",
        path: "/andrology/tesa",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 7,
        title: "IUI Check List",
        path: "/andrology/iui-check-list",
        icon: null,
        onSelect: () => {},
      },
    ],
  },
  {
    id: 10,
    title: "Embryology",
    path: "/embryology",
    icon: ArticleIcon,
    onSelect: () => {},
    isAccordion: true,
    accordionItems: [
      {
        id: 0,
        title: "Lab Records",
        path: "/embryology/lab-records",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 1,
        title: "Summary",
        path: "/embryology/summary",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 2,
        title: "ART Report",
        path: "/embryology/art-report",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 3,
        title: "Cryo Preservation",
        path: "/embryology/cryo-preservation",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 4,
        title: "FET Discharge",
        path: "/embryology/fet-discharge",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 5,
        title: "Donor Embryo Transfer",
        path: "/embryology/donor-embryo-transfer",
        icon: null,
        onSelect: () => {},
      },
      {
        id: 6,
        title: "IVF Check List",
        path: "/embryology/ivf-check-list",
        icon: null,
        onSelect: () => {},
      },
    ],
  },
  {
    id: 11,
    title: "Billing",
    path: "/billing",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 12,
    title: "Pharmacy Sales",
    path: "/pharmacy-sales",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 13,
    title: "Embryology Consumables",
    path: "/embryology-consumables",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 14,
    title: "Appointments",
    path: "/appointments",
    icon: ArticleIcon,
    onSelect: () => {},
  },
  {
    id: 14,
    title: "Documents",
    path: "/documents",
    icon: ArticleIcon,
    onSelect: () => {},
  },
];
