import * as Yup from "yup";

export const PatientRegistrationValidationSchema = Yup.object().shape({
  title: Yup.string(),
  firstName: Yup.string().required("First name is required"),
  lastName: Yup.string().required("Last name is required"),
  gender: Yup.string(),
  age: Yup.number().positive().integer().required("Age is required"),
  dob: Yup.string(),
  education: Yup.string(),
  maritalStatus: Yup.string(),
  bloodGroup: Yup.string(),
  countryBirth: Yup.string(),
  nationality: Yup.string(),
  motherTounge: Yup.string(),
  occupation: Yup.string(),
  religion: Yup.string(),
  mobile: Yup.string().required("Mobile number is required"),
  alernativeMobile: Yup.string(),
  email: Yup.string()
    .email("Invalid email format")
    .required("Email is required"),
  dependentType: Yup.string(),
  dependentName: Yup.string(),
  dependentRelation: Yup.string(),
  dependentMobile: Yup.string(),
  dependentEmail: Yup.string().email("Invalid email format"),
  addressLine1: Yup.string().required("Address Line 1 is required"),
  addressLine2: Yup.string(),
  state: Yup.string().required("State is required"),
  city: Yup.string().required("City is required"),
  pincode: Yup.string(),
  // country: Yup.string().required("Country is required"),
  idProofType: Yup.string(),
  idProofNumber: Yup.string(),
  idProofIssuedCountry: Yup.string(),
  ABHANumber: Yup.string(),
  reasonOfVisit: Yup.string(),
  referredBy: Yup.string(),
  referredByOther: Yup.string(),
  referredByDoctor: Yup.string(),
  marketingSource: Yup.string(),
  intepreter: Yup.boolean(),
  intepreteName: Yup.string(),
  isPatientSurrogate: Yup.boolean(),
  isPatientDeceased: Yup.boolean(),
  detailsOfDeath: Yup.string(),
  isPatientInsured: Yup.boolean(),
  // insuranceCompany: Yup.string(),
  insuranceSponsorName: Yup.string(),
  insurancePolicyNumber: Yup.string(),
  insurancePolicyHolderName: Yup.string(),
  insuranceAmountEligible: Yup.string(),
  image: Yup.mixed(),
  remarks: Yup.string(),
});
